language: python
sudo: false
python:
  - 2.7
  - 3.5
  - 3.6
  - pypy-5.4.1
script:
  - coverage run -m zope.testrunner --test-path=src  --auto-color --auto-progress

after_success:
  - coveralls
notifications:
  email: false

install:
  - pip install -U pip setuptools
  - pip install -U coveralls coverage
# XXX: Remove when https://github.com/zopefoundation/zope.app.http/pull/2 is fixed
  - pip install git+https://github.com/zopefoundation/zope.app.http.git@put-content-type#egg=zope.app.http
  - pip install -U -e ".[test]"


cache: pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
